[package]
name = "iminversed/parametricmovement"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "default.project.json",
    "src/**",
    "src",
    "wally.toml",
    "README.md",
]
exclude = ["**"]

[dependencies]